/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/Heimdall/OTASystemManagementSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createOTASystemManagementSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< OTASystemManagementSomeIPProxy>(_address, _connection);
}

void initializeOTASystemManagementSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:Heimdall.OTASystemManagement:v1_0:Heimdall.OTASystemManagement",
        0x1234, 0x1, 0, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "Heimdall.OTASystemManagement:v1_0",
        &createOTASystemManagementSomeIPProxy);
}

INITIALIZER(registerOTASystemManagementSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeOTASystemManagementSomeIPProxy);
}

OTASystemManagementSomeIPProxy::OTASystemManagementSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          currentState_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x1), CommonAPI::SomeIP::event_id_t(0x8041), CommonAPI::SomeIP::method_id_t(0x40), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, &::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment),
          latestVersion_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x1), CommonAPI::SomeIP::event_id_t(0x8001), CommonAPI::SomeIP::method_id_t(0x10), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
          imageURL_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x1), CommonAPI::SomeIP::event_id_t(0x8021), CommonAPI::SomeIP::method_id_t(0x20), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
          checksumURL_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x1), CommonAPI::SomeIP::event_id_t(0x8031), CommonAPI::SomeIP::method_id_t(0x30), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
          newUpdateAvailable_(*this, 0x1, CommonAPI::SomeIP::event_id_t(0x8010), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
{
}

OTASystemManagementSomeIPProxy::~OTASystemManagementSomeIPProxy() {
}

OTASystemManagementSomeIPProxy::CurrentStateAttribute& OTASystemManagementSomeIPProxy::getCurrentStateAttribute() {
    return currentState_;
}
OTASystemManagementSomeIPProxy::LatestVersionAttribute& OTASystemManagementSomeIPProxy::getLatestVersionAttribute() {
    return latestVersion_;
}
OTASystemManagementSomeIPProxy::ImageURLAttribute& OTASystemManagementSomeIPProxy::getImageURLAttribute() {
    return imageURL_;
}
OTASystemManagementSomeIPProxy::ChecksumURLAttribute& OTASystemManagementSomeIPProxy::getChecksumURLAttribute() {
    return checksumURL_;
}

OTASystemManagementSomeIPProxy::NewUpdateAvailableEvent& OTASystemManagementSomeIPProxy::getNewUpdateAvailableEvent() {
    return newUpdateAvailable_;
}

void OTASystemManagementSomeIPProxy::CheckForUpdates(std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, std::string &_latestVersion, std::string &_imageURL, std::string &_checksumURL, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_clientID(_clientID, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_latestVersion(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_imageURL(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_checksumURL(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_clientID,
        _internalCallStatus,
        deploy_latestVersion, deploy_imageURL, deploy_checksumURL);
    _latestVersion = deploy_latestVersion.getValue();
    _imageURL = deploy_imageURL.getValue();
    _checksumURL = deploy_checksumURL.getValue();
}

std::future<CommonAPI::CallStatus> OTASystemManagementSomeIPProxy::CheckForUpdatesAsync(const std::string &_clientID, CheckForUpdatesAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_clientID(_clientID, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_latestVersion(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_imageURL(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_checksumURL(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_clientID,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _latestVersion, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _imageURL, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _checksumURL) {
            if (_callback)
                _callback(_internalCallStatus, _latestVersion.getValue(), _imageURL.getValue(), _checksumURL.getValue());
        },
        std::make_tuple(deploy_latestVersion, deploy_imageURL, deploy_checksumURL));
}

void OTASystemManagementSomeIPProxy::ReportState(OTASystemManagement::UpdateState _clientState, std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, bool &_acknowledged, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< OTASystemManagement::UpdateState, ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t> deploy_clientState(_clientState, &::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment);
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_clientID(_clientID, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_acknowledged(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTASystemManagement::UpdateState,
                ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_clientState, deploy_clientID,
        _internalCallStatus,
        deploy_acknowledged);
    _acknowledged = deploy_acknowledged.getValue();
}

std::future<CommonAPI::CallStatus> OTASystemManagementSomeIPProxy::ReportStateAsync(const OTASystemManagement::UpdateState &_clientState, const std::string &_clientID, ReportStateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< OTASystemManagement::UpdateState, ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t> deploy_clientState(_clientState, &::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment);
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_clientID(_clientID, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_acknowledged(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTASystemManagement::UpdateState,
                ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_clientState, deploy_clientID,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment > _acknowledged) {
            if (_callback)
                _callback(_internalCallStatus, _acknowledged.getValue());
        },
        std::make_tuple(deploy_acknowledged));
}

void OTASystemManagementSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 0;
}

std::future<void> OTASystemManagementSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace Heimdall
} // namespace v1
