/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_HEIMDALL_OTA_System_Management_SOMEIP_DEPLOYMENT_HPP_
#define V1_HEIMDALL_OTA_System_Management_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {
namespace OTASystemManagement_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> UpdateStateDeployment_t;

// Type-specific deployments
COMMONAPI_EXPORT extern UpdateStateDeployment_t UpdateStateDeployment;

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace OTASystemManagement_
} // namespace Heimdall
} // namespace v1

#endif // V1_HEIMDALL_OTA_System_Management_SOMEIP_DEPLOYMENT_HPP_
