/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_SOMEIP_PROXY_HPP_
#define V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_SOMEIP_PROXY_HPP_

#include <v1/Heimdall/OTASystemManagementProxyBase.hpp>
#include <v1/Heimdall/OTASystemManagementSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Attribute.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace Heimdall {

class OTASystemManagementSomeIPProxy
    : virtual public OTASystemManagementProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    OTASystemManagementSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~OTASystemManagementSomeIPProxy();

    virtual CurrentStateAttribute& getCurrentStateAttribute();

    virtual LatestVersionAttribute& getLatestVersionAttribute();

    virtual ImageURLAttribute& getImageURLAttribute();

    virtual ChecksumURLAttribute& getChecksumURLAttribute();

    virtual NewUpdateAvailableEvent& getNewUpdateAvailableEvent();

    virtual void CheckForUpdates(std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, std::string &_latestVersion, std::string &_imageURL, std::string &_checksumURL, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> CheckForUpdatesAsync(const std::string &_clientID, CheckForUpdatesAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void ReportState(OTASystemManagement::UpdateState _clientState, std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, bool &_acknowledged, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> ReportStateAsync(const OTASystemManagement::UpdateState &_clientState, const std::string &_clientID, ReportStateAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    class SomeIPcurrentState_Attribute : public CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<CurrentStateAttribute, ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t>> {
    public:
        template <typename... _A>
            SomeIPcurrentState_Attribute(OTASystemManagementSomeIPProxy &_proxy,
                _A ... arguments) : CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<CurrentStateAttribute, ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t>>(
                                        _proxy, arguments...) {}
    };
    SomeIPcurrentState_Attribute currentState_;

    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<LatestVersionAttribute, CommonAPI::SomeIP::StringDeployment>> latestVersion_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<ImageURLAttribute, CommonAPI::SomeIP::StringDeployment>> imageURL_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<ChecksumURLAttribute, CommonAPI::SomeIP::StringDeployment>> checksumURL_;
    CommonAPI::SomeIP::Event<NewUpdateAvailableEvent, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >> newUpdateAvailable_;

};

} // namespace Heimdall
} // namespace v1

#endif // V1_HEIMDALL_OTA_System_Management_SOMEIP_PROXY_HPP_
