/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_SOMEIP_STUB_ADAPTER_HPP_
#define V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/Heimdall/OTASystemManagementStub.hpp>
#include <v1/Heimdall/OTASystemManagementSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {

template <typename _Stub = ::v1::Heimdall::OTASystemManagementStub, typename... _Stubs>
class OTASystemManagementSomeIPStubAdapterInternal
    : public virtual OTASystemManagementStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> OTASystemManagementSomeIPStubAdapterHelper;

    ~OTASystemManagementSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        OTASystemManagementSomeIPStubAdapterHelper::deinit();
    }

    void fireCurrentStateAttributeChanged(const ::v1::Heimdall::OTASystemManagement::UpdateState &_value);
    
    void fireLatestVersionAttributeChanged(const std::string &_value);
    
    void fireImageURLAttributeChanged(const std::string &_value);
    
    void fireChecksumURLAttributeChanged(const std::string &_value);
    
    void fireNewUpdateAvailableEvent(const std::string &_latestVersion, const std::string &_imageURL, const std::string &_checksumURL);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        CommonAPI::Version
    > getOTASystemManagementInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        ::v1::Heimdall::OTASystemManagement::UpdateState,
        ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t
    > getCurrentStateAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getLatestVersionAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getImageURLAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getChecksumURLAttributeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        std::tuple< std::string>,
        std::tuple< std::string, std::string, std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, CommonAPI::SomeIP::StringDeployment, CommonAPI::SomeIP::StringDeployment>
    > checkForUpdatesStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::Heimdall::OTASystemManagementStub,
        std::tuple< OTASystemManagement::UpdateState, std::string>,
        std::tuple< bool>,
        std::tuple< ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t, CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    > reportStateStubDispatcher;
    
    OTASystemManagementSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        OTASystemManagementSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< OTASystemManagementStub>(_stub)),
        getOTASystemManagementInterfaceVersionStubDispatcher(&OTASystemManagementStub::lockInterfaceVersionAttribute, &OTASystemManagementStub::getInterfaceVersion, false, true),
        getCurrentStateAttributeStubDispatcher(
            &::v1::Heimdall::OTASystemManagementStub::lockCurrentStateAttribute,
            &::v1::Heimdall::OTASystemManagementStub::getCurrentStateAttribute,
            false,
            _stub->hasElement(2), &::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment)
        ,
        getLatestVersionAttributeStubDispatcher(
            &::v1::Heimdall::OTASystemManagementStub::lockLatestVersionAttribute,
            &::v1::Heimdall::OTASystemManagementStub::getLatestVersionAttribute,
            false,
            _stub->hasElement(3))
        ,
        getImageURLAttributeStubDispatcher(
            &::v1::Heimdall::OTASystemManagementStub::lockImageURLAttribute,
            &::v1::Heimdall::OTASystemManagementStub::getImageURLAttribute,
            false,
            _stub->hasElement(4))
        ,
        getChecksumURLAttributeStubDispatcher(
            &::v1::Heimdall::OTASystemManagementStub::lockChecksumURLAttribute,
            &::v1::Heimdall::OTASystemManagementStub::getChecksumURLAttribute,
            false,
            _stub->hasElement(5))
        ,
        checkForUpdatesStubDispatcher(
            &OTASystemManagementStub::CheckForUpdates,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        reportStateStubDispatcher(
            &OTASystemManagementStub::ReportState,
            false,
            _stub->hasElement(1),
            std::make_tuple(&::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
    {
        OTASystemManagementSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x40) }, &getCurrentStateAttributeStubDispatcher );
        OTASystemManagementSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x10) }, &getLatestVersionAttributeStubDispatcher );
        OTASystemManagementSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x20) }, &getImageURLAttributeStubDispatcher );
        OTASystemManagementSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x30) }, &getChecksumURLAttributeStubDispatcher );
        OTASystemManagementSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &checkForUpdatesStubDispatcher );
        OTASystemManagementSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2) }, &reportStateStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x1));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8010), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        if (_stub->hasElement(2)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8041), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireCurrentStateAttributeChanged(std::dynamic_pointer_cast< ::v1::Heimdall::OTASystemManagementStub>(_stub)->getCurrentStateAttribute(itsClient));
        }

        if (_stub->hasElement(3)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8001), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireLatestVersionAttributeChanged(std::dynamic_pointer_cast< ::v1::Heimdall::OTASystemManagementStub>(_stub)->getLatestVersionAttribute(itsClient));
        }

        if (_stub->hasElement(4)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8021), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireImageURLAttributeChanged(std::dynamic_pointer_cast< ::v1::Heimdall::OTASystemManagementStub>(_stub)->getImageURLAttribute(itsClient));
        }

        if (_stub->hasElement(5)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8031), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireChecksumURLAttributeChanged(std::dynamic_pointer_cast< ::v1::Heimdall::OTASystemManagementStub>(_stub)->getChecksumURLAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireCurrentStateAttributeChanged(const ::v1::Heimdall::OTASystemManagement::UpdateState &_value) {
    CommonAPI::Deployable< ::v1::Heimdall::OTASystemManagement::UpdateState, ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t> deployedValue(_value, &::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment);
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::Heimdall::OTASystemManagement::UpdateState,
                ::v1::Heimdall::OTASystemManagement_::UpdateStateDeployment_t
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x8041),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireLatestVersionAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x8001),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireImageURLAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x8021),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireChecksumURLAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x8031),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireNewUpdateAvailableEvent(const std::string &_latestVersion, const std::string &_imageURL, const std::string &_checksumURL) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_latestVersion(_latestVersion, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_imageURL(_imageURL, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_checksumURL(_checksumURL, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    ,  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    ,  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8010),
            false,
             deployed_latestVersion 
            ,  deployed_imageURL 
            ,  deployed_checksumURL 
    );
}


template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::Heimdall::OTASystemManagementStub, typename... _Stubs>
class OTASystemManagementSomeIPStubAdapter
    : public OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    OTASystemManagementSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          OTASystemManagementSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace Heimdall
} // namespace v1

#endif // V1_HEIMDALL_OTA_System_Management_SOMEIP_STUB_ADAPTER_HPP_
