/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_HEIMDALL_OTA_System_Management_STUB_HPP_
#define V1_HEIMDALL_OTA_System_Management_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/Heimdall/OTASystemManagement.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service OTASystemManagement. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class OTASystemManagementStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual OTASystemManagement {
 public:
    ///Notifies all remote listeners about a change of value of the attribute currentState.
    virtual void fireCurrentStateAttributeChanged(const ::v1::Heimdall::OTASystemManagement::UpdateState &currentState) = 0;
    ///Notifies all remote listeners about a change of value of the attribute latestVersion.
    virtual void fireLatestVersionAttributeChanged(const std::string &latestVersion) = 0;
    ///Notifies all remote listeners about a change of value of the attribute imageURL.
    virtual void fireImageURLAttributeChanged(const std::string &imageURL) = 0;
    ///Notifies all remote listeners about a change of value of the attribute checksumURL.
    virtual void fireChecksumURLAttributeChanged(const std::string &checksumURL) = 0;
    /**
    * Sends a broadcast event for newUpdateAvailable. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireNewUpdateAvailableEvent(const std::string &_latestVersion, const std::string &_imageURL, const std::string &_checksumURL) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockCurrentStateAttribute(bool _lockAccess) {
        if (_lockAccess) {
            currentStateMutex_.lock();
        } else {
            currentStateMutex_.unlock();
        }
    }
    void lockLatestVersionAttribute(bool _lockAccess) {
        if (_lockAccess) {
            latestVersionMutex_.lock();
        } else {
            latestVersionMutex_.unlock();
        }
    }
    void lockImageURLAttribute(bool _lockAccess) {
        if (_lockAccess) {
            imageURLMutex_.lock();
        } else {
            imageURLMutex_.unlock();
        }
    }
    void lockChecksumURLAttribute(bool _lockAccess) {
        if (_lockAccess) {
            checksumURLMutex_.lock();
        } else {
            checksumURLMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex currentStateMutex_;
    std::recursive_mutex latestVersionMutex_;
    std::recursive_mutex imageURLMutex_;
    std::recursive_mutex checksumURLMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for OTASystemManagement.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class OTASystemManagementStubRemoteEvent
{
public:
    virtual ~OTASystemManagementStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service OTASystemManagement to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class OTASystemManagementStub
    : public virtual CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>
{
public:
    typedef std::function<void (std::string _latestVersion, std::string _imageURL, std::string _checksumURL)> CheckForUpdatesReply_t;
    typedef std::function<void (bool _acknowledged)> ReportStateReply_t;

    virtual ~OTASystemManagementStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 7);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method CheckForUpdates.
    virtual void CheckForUpdates(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _clientID, CheckForUpdatesReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method ReportState.
    virtual void ReportState(const std::shared_ptr<CommonAPI::ClientId> _client, OTASystemManagement::UpdateState _clientState, std::string _clientID, ReportStateReply_t _reply) = 0;
    /// Provides getter access to the attribute currentState
    virtual const ::v1::Heimdall::OTASystemManagement::UpdateState &getCurrentStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireCurrentStateAttributeChanged(::v1::Heimdall::OTASystemManagement::UpdateState _value) {
    auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireCurrentStateAttributeChanged(_value);
    }
    void lockCurrentStateAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockCurrentStateAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute latestVersion
    virtual const std::string &getLatestVersionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireLatestVersionAttributeChanged(std::string _value) {
    auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireLatestVersionAttributeChanged(_value);
    }
    void lockLatestVersionAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockLatestVersionAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute imageURL
    virtual const std::string &getImageURLAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireImageURLAttributeChanged(std::string _value) {
    auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireImageURLAttributeChanged(_value);
    }
    void lockImageURLAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockImageURLAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute checksumURL
    virtual const std::string &getChecksumURLAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireChecksumURLAttributeChanged(std::string _value) {
    auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireChecksumURLAttributeChanged(_value);
    }
    void lockChecksumURLAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockChecksumURLAttribute(_lockAccess);
    }
    /// Sends a broadcast event for newUpdateAvailable.
    virtual void fireNewUpdateAvailableEvent(const std::string &_latestVersion, const std::string &_imageURL, const std::string &_checksumURL) {
        auto stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireNewUpdateAvailableEvent(_latestVersion, _imageURL, _checksumURL);
    }


    using CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef OTASystemManagementStubRemoteEvent RemoteEventType;
    typedef ::v1::Heimdall::OTASystemManagement StubInterface;
};

} // namespace Heimdall
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_HEIMDALL_OTA_System_Management_STUB_HPP_
