/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_HPP_
#define V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {

class OTASystemManagement {
public:
    virtual ~OTASystemManagement() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct UpdateState : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            IDLE = 0,
            UPDATE_AVAILABLE = 1,
            DOWNLOADING = 2,
            VERIFYING = 3,
            INSTALLING = 4,
            REBOOT_REQUIRED = 5,
            ERROR = 6
        };
    
        UpdateState()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::IDLE)) {}
        UpdateState(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::IDLE):
                case static_cast< uint8_t>(Literal::UPDATE_AVAILABLE):
                case static_cast< uint8_t>(Literal::DOWNLOADING):
                case static_cast< uint8_t>(Literal::VERIFYING):
                case static_cast< uint8_t>(Literal::INSTALLING):
                case static_cast< uint8_t>(Literal::REBOOT_REQUIRED):
                case static_cast< uint8_t>(Literal::ERROR):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const UpdateState &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const UpdateState &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const UpdateState &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const UpdateState &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const UpdateState &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const UpdateState &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::IDLE): return "IDLE";
            case static_cast< uint8_t>(Literal::UPDATE_AVAILABLE): return "UPDATE_AVAILABLE";
            case static_cast< uint8_t>(Literal::DOWNLOADING): return "DOWNLOADING";
            case static_cast< uint8_t>(Literal::VERIFYING): return "VERIFYING";
            case static_cast< uint8_t>(Literal::INSTALLING): return "INSTALLING";
            case static_cast< uint8_t>(Literal::REBOOT_REQUIRED): return "REBOOT_REQUIRED";
            case static_cast< uint8_t>(Literal::ERROR): return "ERROR";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* OTASystemManagement::getInterface() {
    return ("Heimdall.OTASystemManagement:v1_0");
}

CommonAPI::Version OTASystemManagement::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace Heimdall
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_HEIMDALL_OTA_SYSTEM_MANAGEMENT_HPP_
