/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_HEIMDALL_OTA_System_Management_STUB_DEFAULT_HPP_
#define V1_HEIMDALL_OTA_System_Management_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/Heimdall/OTASystemManagementStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace Heimdall {

/**
 * Provides a default implementation for OTASystemManagementStubRemoteEvent and
 * OTASystemManagementStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT OTASystemManagementStubDefault
    : public virtual OTASystemManagementStub {
public:
    COMMONAPI_EXPORT OTASystemManagementStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(OTASystemManagement::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT OTASystemManagementStubRemoteEvent* initStubAdapter(const std::shared_ptr< OTASystemManagementStubAdapter> &_adapter) {
        CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void CheckForUpdates(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _clientID, CheckForUpdatesReply_t _reply) {
        (void)_client;
        (void)_clientID;
        std::string latestVersion = "";
        std::string imageURL = "";
        std::string checksumURL = "";
        _reply(latestVersion, imageURL, checksumURL);
    }
    COMMONAPI_EXPORT virtual void ReportState(const std::shared_ptr<CommonAPI::ClientId> _client, OTASystemManagement::UpdateState _clientState, std::string _clientID, ReportStateReply_t _reply) {
        (void)_client;
        (void)_clientState;
        (void)_clientID;
        bool acknowledged = false;
        _reply(acknowledged);
    }
    COMMONAPI_EXPORT virtual const ::v1::Heimdall::OTASystemManagement::UpdateState &getCurrentStateAttribute() {
        return currentStateAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const ::v1::Heimdall::OTASystemManagement::UpdateState &getCurrentStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getCurrentStateAttribute();
    }
    COMMONAPI_EXPORT virtual void setCurrentStateAttribute(::v1::Heimdall::OTASystemManagement::UpdateState _value) {
        const bool valueChanged = trySetCurrentStateAttribute(std::move(_value));
        if (valueChanged) {
            fireCurrentStateAttributeChanged(currentStateAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getLatestVersionAttribute() {
        return latestVersionAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getLatestVersionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getLatestVersionAttribute();
    }
    COMMONAPI_EXPORT virtual void setLatestVersionAttribute(std::string _value) {
        const bool valueChanged = trySetLatestVersionAttribute(std::move(_value));
        if (valueChanged) {
            fireLatestVersionAttributeChanged(latestVersionAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getImageURLAttribute() {
        return imageURLAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getImageURLAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getImageURLAttribute();
    }
    COMMONAPI_EXPORT virtual void setImageURLAttribute(std::string _value) {
        const bool valueChanged = trySetImageURLAttribute(std::move(_value));
        if (valueChanged) {
            fireImageURLAttributeChanged(imageURLAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getChecksumURLAttribute() {
        return checksumURLAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getChecksumURLAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getChecksumURLAttribute();
    }
    COMMONAPI_EXPORT virtual void setChecksumURLAttribute(std::string _value) {
        const bool valueChanged = trySetChecksumURLAttribute(std::move(_value));
        if (valueChanged) {
            fireChecksumURLAttributeChanged(checksumURLAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void fireNewUpdateAvailableEvent(const std::string &_latestVersion, const std::string &_imageURL, const std::string &_checksumURL) {
        OTASystemManagementStub::fireNewUpdateAvailableEvent(_latestVersion, _imageURL, _checksumURL);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetCurrentStateAttribute(::v1::Heimdall::OTASystemManagement::UpdateState _value) {
        if (!validateCurrentStateAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<OTASystemManagementStubAdapter> stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockCurrentStateAttribute(true);
            valueChanged = (currentStateAttributeValue_ != _value);
            currentStateAttributeValue_ = std::move(_value);
            stubAdapter->lockCurrentStateAttribute(false);
        } else {
            valueChanged = (currentStateAttributeValue_ != _value);
            currentStateAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateCurrentStateAttributeRequestedValue(const ::v1::Heimdall::OTASystemManagement::UpdateState &_value) {
        (void)_value;
        return _value.validate();
    }
    COMMONAPI_EXPORT virtual bool trySetLatestVersionAttribute(std::string _value) {
        if (!validateLatestVersionAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<OTASystemManagementStubAdapter> stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockLatestVersionAttribute(true);
            valueChanged = (latestVersionAttributeValue_ != _value);
            latestVersionAttributeValue_ = std::move(_value);
            stubAdapter->lockLatestVersionAttribute(false);
        } else {
            valueChanged = (latestVersionAttributeValue_ != _value);
            latestVersionAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateLatestVersionAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetImageURLAttribute(std::string _value) {
        if (!validateImageURLAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<OTASystemManagementStubAdapter> stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockImageURLAttribute(true);
            valueChanged = (imageURLAttributeValue_ != _value);
            imageURLAttributeValue_ = std::move(_value);
            stubAdapter->lockImageURLAttribute(false);
        } else {
            valueChanged = (imageURLAttributeValue_ != _value);
            imageURLAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateImageURLAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetChecksumURLAttribute(std::string _value) {
        if (!validateChecksumURLAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<OTASystemManagementStubAdapter> stubAdapter = CommonAPI::Stub<OTASystemManagementStubAdapter, OTASystemManagementStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockChecksumURLAttribute(true);
            valueChanged = (checksumURLAttributeValue_ != _value);
            checksumURLAttributeValue_ = std::move(_value);
            stubAdapter->lockChecksumURLAttribute(false);
        } else {
            valueChanged = (checksumURLAttributeValue_ != _value);
            checksumURLAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateChecksumURLAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual OTASystemManagementStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(OTASystemManagementStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        OTASystemManagementStubDefault *defaultStub_;
    };
protected:
    OTASystemManagementStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    ::v1::Heimdall::OTASystemManagement::UpdateState currentStateAttributeValue_ {};
    std::string latestVersionAttributeValue_ {};
    std::string imageURLAttributeValue_ {};
    std::string checksumURLAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace Heimdall
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_HEIMDALL_OTA_System_Management_STUB_DEFAULT
