/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_HEIMDALL_OTA_System_Management_PROXY_BASE_HPP_
#define V1_HEIMDALL_OTA_System_Management_PROXY_BASE_HPP_

#include <v1/Heimdall/OTASystemManagement.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {

class OTASystemManagementProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableReadonlyAttribute<::v1::Heimdall::OTASystemManagement::UpdateState> CurrentStateAttribute;
    typedef CommonAPI::ObservableReadonlyAttribute<std::string> LatestVersionAttribute;
    typedef CommonAPI::ObservableReadonlyAttribute<std::string> ImageURLAttribute;
    typedef CommonAPI::ObservableReadonlyAttribute<std::string> ChecksumURLAttribute;
    typedef CommonAPI::Event<
        std::string, std::string, std::string
    > NewUpdateAvailableEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&, const std::string&, const std::string&)> CheckForUpdatesAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const bool&)> ReportStateAsyncCallback;

    virtual void CheckForUpdates(std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, std::string &_latestVersion, std::string &_imageURL, std::string &_checksumURL, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> CheckForUpdatesAsync(const std::string &_clientID, CheckForUpdatesAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void ReportState(OTASystemManagement::UpdateState _clientState, std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, bool &_acknowledged, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> ReportStateAsync(const OTASystemManagement::UpdateState &_clientState, const std::string &_clientID, ReportStateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual CurrentStateAttribute& getCurrentStateAttribute() = 0;
    virtual LatestVersionAttribute& getLatestVersionAttribute() = 0;
    virtual ImageURLAttribute& getImageURLAttribute() = 0;
    virtual ChecksumURLAttribute& getChecksumURLAttribute() = 0;
    virtual NewUpdateAvailableEvent& getNewUpdateAvailableEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace Heimdall
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_HEIMDALL_OTA_System_Management_PROXY_BASE_HPP_
