/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_HEIMDALL_OTA_System_Management_PROXY_HPP_
#define V1_HEIMDALL_OTA_System_Management_PROXY_HPP_

#include <v1/Heimdall/OTASystemManagementProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Heimdall {

template <typename ... _AttributeExtensions>
class OTASystemManagementProxy
    : virtual public OTASystemManagement,
      virtual public OTASystemManagementProxyBase,
      virtual public _AttributeExtensions... {
public:
    OTASystemManagementProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~OTASystemManagementProxy();

    typedef ::v1::Heimdall::OTASystemManagement InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls CheckForUpdates with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void CheckForUpdates(std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, std::string &_latestVersion, std::string &_imageURL, std::string &_checksumURL, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls CheckForUpdates with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> CheckForUpdatesAsync(const std::string &_clientID, CheckForUpdatesAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls ReportState with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void ReportState(OTASystemManagement::UpdateState _clientState, std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, bool &_acknowledged, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls ReportState with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> ReportStateAsync(const OTASystemManagement::UpdateState &_clientState, const std::string &_clientID, ReportStateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the attribute currentState.
     */
    virtual CurrentStateAttribute& getCurrentStateAttribute() {
        return delegate_->getCurrentStateAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute latestVersion.
     */
    virtual LatestVersionAttribute& getLatestVersionAttribute() {
        return delegate_->getLatestVersionAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute imageURL.
     */
    virtual ImageURLAttribute& getImageURLAttribute() {
        return delegate_->getImageURLAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute checksumURL.
     */
    virtual ChecksumURLAttribute& getChecksumURLAttribute() {
        return delegate_->getChecksumURLAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast newUpdateAvailable.
     */
    virtual NewUpdateAvailableEvent& getNewUpdateAvailableEvent() {
        return delegate_->getNewUpdateAvailableEvent();
    }



 private:
    std::shared_ptr< OTASystemManagementProxyBase> delegate_;
};

typedef OTASystemManagementProxy<> OTASystemManagementProxyDefault;

namespace OTASystemManagementExtensions {
    template <template <typename > class _ExtensionType>
    class CurrentStateAttributeExtension {
     public:
        typedef _ExtensionType< OTASystemManagementProxyBase::CurrentStateAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< OTASystemManagementProxyBase::CurrentStateAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        CurrentStateAttributeExtension(OTASystemManagementProxyBase& proxy): attributeExtension_(proxy.getCurrentStateAttribute()) {
        }
    
        inline extension_type& getCurrentStateAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class LatestVersionAttributeExtension {
     public:
        typedef _ExtensionType< OTASystemManagementProxyBase::LatestVersionAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< OTASystemManagementProxyBase::LatestVersionAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        LatestVersionAttributeExtension(OTASystemManagementProxyBase& proxy): attributeExtension_(proxy.getLatestVersionAttribute()) {
        }
    
        inline extension_type& getLatestVersionAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class ImageURLAttributeExtension {
     public:
        typedef _ExtensionType< OTASystemManagementProxyBase::ImageURLAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< OTASystemManagementProxyBase::ImageURLAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ImageURLAttributeExtension(OTASystemManagementProxyBase& proxy): attributeExtension_(proxy.getImageURLAttribute()) {
        }
    
        inline extension_type& getImageURLAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class ChecksumURLAttributeExtension {
     public:
        typedef _ExtensionType< OTASystemManagementProxyBase::ChecksumURLAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< OTASystemManagementProxyBase::ChecksumURLAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ChecksumURLAttributeExtension(OTASystemManagementProxyBase& proxy): attributeExtension_(proxy.getChecksumURLAttribute()) {
        }
    
        inline extension_type& getChecksumURLAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace OTASystemManagementExtensions

//
// OTASystemManagementProxy Implementation
//
template <typename ... _AttributeExtensions>
OTASystemManagementProxy<_AttributeExtensions...>::OTASystemManagementProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< OTASystemManagementProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< OTASystemManagementProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
OTASystemManagementProxy<_AttributeExtensions...>::~OTASystemManagementProxy() {
}

template <typename ... _AttributeExtensions>
void OTASystemManagementProxy<_AttributeExtensions...>::CheckForUpdates(std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, std::string &_latestVersion, std::string &_imageURL, std::string &_checksumURL, const CommonAPI::CallInfo *_info) {
    delegate_->CheckForUpdates(_clientID, _internalCallStatus, _latestVersion, _imageURL, _checksumURL, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OTASystemManagementProxy<_AttributeExtensions...>::CheckForUpdatesAsync(const std::string &_clientID, CheckForUpdatesAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->CheckForUpdatesAsync(_clientID, _callback, _info);
}
template <typename ... _AttributeExtensions>
void OTASystemManagementProxy<_AttributeExtensions...>::ReportState(OTASystemManagement::UpdateState _clientState, std::string _clientID, CommonAPI::CallStatus &_internalCallStatus, bool &_acknowledged, const CommonAPI::CallInfo *_info) {
    if (!_clientState.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->ReportState(_clientState, _clientID, _internalCallStatus, _acknowledged, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OTASystemManagementProxy<_AttributeExtensions...>::ReportStateAsync(const OTASystemManagement::UpdateState &_clientState, const std::string &_clientID, ReportStateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_clientState.validate()) {
        bool acknowledged = false;
        _callback(CommonAPI::CallStatus::INVALID_VALUE, acknowledged);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->ReportStateAsync(_clientState, _clientID, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &OTASystemManagementProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool OTASystemManagementProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool OTASystemManagementProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& OTASystemManagementProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& OTASystemManagementProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> OTASystemManagementProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace Heimdall
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::Heimdall::OTASystemManagementProxy,
    _AttributeExtension> {
    typedef typename ::v1::Heimdall::OTASystemManagementProxy<
            ::v1::Heimdall::OTASystemManagementExtensions::CurrentStateAttributeExtension<_AttributeExtension>, 
            ::v1::Heimdall::OTASystemManagementExtensions::LatestVersionAttributeExtension<_AttributeExtension>, 
            ::v1::Heimdall::OTASystemManagementExtensions::ImageURLAttributeExtension<_AttributeExtension>, 
            ::v1::Heimdall::OTASystemManagementExtensions::ChecksumURLAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_HEIMDALL_OTA_System_Management_PROXY_HPP_
